kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume
  labels:
    tpye: local
spec:
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv0001/"