version: "3.8"

services:
  jenkins:
    build:
      image:
      network_node: "bridge"
      contair_name: jenkins
      ports:
        - "8080:8080"
        - "50000:50000"
      environment:
        JENKINS_USER: Admin
        JENKINS_PASS: Aa123456789
        JAVA_OPTS: "-Djenkins.install.runSetupWizard=true -Djenkins.httpPort=8888"
    volumes:
      - "jenkins_home:"C:\jenkins_home"
      - "~/.kube/config:C:\Users\nyyif\.kube\config"


volumes:
  jenkis_home:

